services:
  react-app:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    container_name: react-build
    working_dir: /app
    command: ["npm", "run", "build"]
    volumes:
      - ./react-app:/app
      - ./react-app/build:/app/build
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    container_name: react-nginx
    ports:
      - "8080:80"
    volumes:
      - ./react-app/build:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
