services:
  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextclouduser
      MYSQL_PASSWORD: example_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud
    container_name: nextcloud-app
    ports:
      - 8080:80
    environment:
      REDIS_HOST: redis
    links:
      - db
      - redis
    volumes:
      - nextcloud_data:/var/www/html
      - ./patch-config.sh:/docker-entrypoint-init.d/patch-config.sh
    depends_on:
      - db
      - redis

  init:
    image: nextcloud
    depends_on:
      - app
    volumes:
      - nextcloud_data:/var/www/html
      - ./init-redis.sh:/docker-entrypoint-init.d/init-redis.sh
    entrypoint: ["bash", "/docker-entrypoint-init.d/init-redis.sh"]

volumes:
  db_data:
  nextcloud_data:
