resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      productService:
        baseConfig: default
      orderService:
        baseConfig: default

  retry:
    configs:
      default:
        maxAttempts: 5
        waitDuration: 500ms
    instances:
      productService:
        baseConfig: default
      orderService:
        baseConfig: default

  ratelimiter:
    configs:
      default:
        limitForPeriod: 2
        limitRefreshPeriod: 10s
    instances:
      productService:
        baseConfig: default
      orderService:
        baseConfig: default