services:
  redis:
    image: redis:latest
    container_name: redis-limited
    ports:
      - "6379:6379"
    restart: always
    mem_limit: 100m         # RAM giới hạn 100MB
    cpus: 0.5               # CPU giới hạn 50% 1 core