services:
  vote:
    build: ./vote
    ports:
      - "5000:80"
    depends_on:
      - redis

  result:
    build: ./result
    ports:
      - "5001:80"
    depends_on:
      - db

  worker:
    build: ./worker
    depends_on:
      - redis
      - db

  redis:
    image: redis:alpine

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: votes
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
