services:
  server:
    build:
      context: ./server
    container_name: flask-server
    networks:
      - mynet
    ports:
      - "5000:5000"

  client:
    image: alpine
    container_name: alpine-client
    command: sh -c "apk add curl && sleep 5 && curl http://server:5000"
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
