services:
  django:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=django_project.settings
    depends_on:
      - redis

  celery:
    build: .
    command: celery -A django_project worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=django_project.settings

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
